name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
          chmod +x ./gradlew
          ./gradlew build
    - uses: actions/upload-artifact@v1
      with:
        name: kibe
        path: build/libs/
