name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2.2.0
    - name: Build
      run: |
          chmod +x ./gradlew
          ./gradlew build
    - uses: actions/upload-artifact@v2
      with:
        name: main-jar
        path: build/libs/*-*.jar
    - uses: actions/upload-artifact@v2
      with:
        name: sources-jar
        path: build/libs/*-*-sources.jar
